version: '3.4'

services: 

    edge-proxy: 
        image: nginx:1.19.1
        volumes: 
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks: 
            - edge
        ports: 
            - 80:80

    localhost1_1:
        image: viniqsoares/routing-troubleshooting-api
        environment: 
            - APP_NAME=localhost1_Instancia1
        networks: 
            - edge
    localhost1_2:
        image: viniqsoares/routing-troubleshooting-api
        environment: 
            - APP_NAME=localhost1_Instancia2
        networks: 
            - edge
    localhost2:
        image: viniqsoares/routing-troubleshooting-api
        environment: 
            - APP_NAME=localhost2
        networks: 
            - edge
    
networks: 
    edge:
        driver: bridge

             